lint:
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - assets/multiqc_config.yml
    - assets/methods_description_template.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-metagenomeassembly_logo_light.png
    - docs/images/nf-core-metagenomeassembly_logo_light.png
    - docs/images/nf-core-metagenomeassembly_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-metagenomeassembly_logo_light.png
    - assets/multiqc_config.yml
    - docs/images/nf-core-metagenomeassembly_logo_light.png
    - docs/images/nf-core-metagenomeassembly_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
  multiqc_config: False
  nextflow_config:
    - process.cpus
    - process.memory
    - process.time
    - custom_config
    - params.custom_config_version
    - params.custom_config_base
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
    - config_defaults:
        - params.hmm_gtdb_pfam
        - params.hmm_gtdb_tigrfam
        - params.rfam_rrna_cm
  readme:
    - nextflow_badge
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Jim Downie, Will Eagles, Noah Gettle
  description: Construct MAGs from long reads.
  force: false
  is_nfcore: false
  name: metagenomeassembly
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - github_badges
    - codespaces
    - fastqc
    - email
    - adaptivecard
    - slackreport
    - seqera_platform
    - multiqc
  version: 1.0.0dev
