channels:
  - conda-forge
  - bioconda
dependencies:
  - requests
  - pip
  - git
  - biopython=1.80
  - bowtie2=2.5.1
  - bwa=0.7.17
  - samtools=1.17
  - prodigal=2.6.3
  - hmmer=3.3.2
  - pysam=0.21.0
  - pairix=0.3.7
  - pairtools=1.0.2
  - pyfastx==0.8.4
  - cooler==0.9.1
  - pandas==1.5.3
  - hicstuff
  - checkm-genome=1.2.3
  - gxx
  - make
  - pip:
      - micomplete==1.1.1
      - metator
      - pytest
      - pylint
      - codecov
      - pytest-cov
      - pytest-pylint
